//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsAzure.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsAzure.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartitionKey or RowKey attribute should be defined for type &apos;{0}&apos;..
        /// </summary>
        internal static string EntityTypeDataMissingKey {
            get {
                return ResourceManager.GetString("EntityTypeDataMissingKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; in type &apos;{1}&apos; should be marked only by one metadata attribute..
        /// </summary>
        internal static string EntityTypeDataShouldBeOneAttribute {
            get {
                return ResourceManager.GetString("EntityTypeDataShouldBeOneAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to cast type &apos;{0}&apos; to target type &apos;{1}&apos;..
        /// </summary>
        internal static string ExpressionEvaluatorInvalidCast {
            get {
                return ResourceManager.GetString("ExpressionEvaluatorInvalidCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; does not supported..
        /// </summary>
        internal static string ExpressionEvaluatorTypeNotSupported {
            get {
                return ResourceManager.GetString("ExpressionEvaluatorTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get value of the node: &apos;{0}&apos;..
        /// </summary>
        internal static string ExpressionEvaluatorUnableToEvaluate {
            get {
                return ResourceManager.GetString("ExpressionEvaluatorUnableToEvaluate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid entity member type: &apos;{0}&apos;..
        /// </summary>
        internal static string ExpressionValueAccessorInvalidMemberType {
            get {
                return ResourceManager.GetString("ExpressionValueAccessorInvalidMemberType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETag must have a string type..
        /// </summary>
        internal static string PropertyETagInvalidType {
            get {
                return ResourceManager.GetString("PropertyETagInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartitionKey must have a string type..
        /// </summary>
        internal static string PropertyPartitionKeyInvalidType {
            get {
                return ResourceManager.GetString("PropertyPartitionKeyInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RowKey must have a string type..
        /// </summary>
        internal static string PropertyRowKeyInvalidType {
            get {
                return ResourceManager.GetString("PropertyRowKeyInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp should be a DateTime type..
        /// </summary>
        internal static string PropertyTimestampInvalidType {
            get {
                return ResourceManager.GetString("PropertyTimestampInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to serialize type: &apos;{0}&apos;..
        /// </summary>
        internal static string SerializationExtensionsNotSupportedType {
            get {
                return ResourceManager.GetString("SerializationExtensionsNotSupportedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty entities collection..
        /// </summary>
        internal static string TableBatchPartitionerNoEntities {
            get {
                return ResourceManager.GetString("TableBatchPartitionerNoEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request execution mode &apos;{0}&apos;..
        /// </summary>
        internal static string TableRequestExecutorInvalidMode {
            get {
                return ResourceManager.GetString("TableRequestExecutorInvalidMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; does not supported..
        /// </summary>
        internal static string TranslatorMemberNotSupported {
            get {
                return ResourceManager.GetString("TranslatorMemberNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid method &apos;{0}&apos; arguments..
        /// </summary>
        internal static string TranslatorMethodInvalidArgument {
            get {
                return ResourceManager.GetString("TranslatorMethodInvalidArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}&apos; does not supported..
        /// </summary>
        internal static string TranslatorMethodNotSupported {
            get {
                return ResourceManager.GetString("TranslatorMethodNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator &apos;{0}&apos; does not supported..
        /// </summary>
        internal static string TranslatorOperatorNotSupported {
            get {
                return ResourceManager.GetString("TranslatorOperatorNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to evaluate an expression: &apos;{0}&apos;..
        /// </summary>
        internal static string TranslatorUnableToEvaluateExpression {
            get {
                return ResourceManager.GetString("TranslatorUnableToEvaluateExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to translate method: &apos;{0}&apos;..
        /// </summary>
        internal static string TranslatorUnableToTranslateMethod {
            get {
                return ResourceManager.GetString("TranslatorUnableToTranslateMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member type &apos;{0}&apos; does not supported..
        /// </summary>
        internal static string ValueAccessorFactoryNotSupportedType {
            get {
                return ResourceManager.GetString("ValueAccessorFactoryNotSupportedType", resourceCulture);
            }
        }
    }
}
