//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsAzure.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsAzure.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartitionKey or RowKey attribute should be defined for type &apos;{0}&apos;..
        /// </summary>
        internal static string EntityTypeDataMissingKey {
            get {
                return ResourceManager.GetString("EntityTypeDataMissingKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETag attribute duplication..
        /// </summary>
        internal static string ETagAttributeDuplicate {
            get {
                return ResourceManager.GetString("ETagAttributeDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETag must have a string type..
        /// </summary>
        internal static string ETagInvalidType {
            get {
                return ResourceManager.GetString("ETagInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; does not supported..
        /// </summary>
        internal static string ExpressionEvaluatorTypeNotSupported {
            get {
                return ResourceManager.GetString("ExpressionEvaluatorTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid entity member type: &apos;{0}&apos;..
        /// </summary>
        internal static string ExpressionValueAccessorInvalidMemberType {
            get {
                return ResourceManager.GetString("ExpressionValueAccessorInvalidMemberType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartitionKey attribute duplication..
        /// </summary>
        internal static string PartitionKeyAttributeDuplicate {
            get {
                return ResourceManager.GetString("PartitionKeyAttributeDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartitionKey must have a string type..
        /// </summary>
        internal static string PartitionKeyInvalidType {
            get {
                return ResourceManager.GetString("PartitionKeyInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}&apos; does not supported..
        /// </summary>
        internal static string QueryTranslatorMethodNotSupported {
            get {
                return ResourceManager.GetString("QueryTranslatorMethodNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RowKey attribute duplication..
        /// </summary>
        internal static string RowKeyAttributeDuplicate {
            get {
                return ResourceManager.GetString("RowKeyAttributeDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RowKey must have a string type..
        /// </summary>
        internal static string RowKeyInvalidType {
            get {
                return ResourceManager.GetString("RowKeyInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to serialize type: &apos;{0}&apos;..
        /// </summary>
        internal static string SerializationExtensionsNotSupportedType {
            get {
                return ResourceManager.GetString("SerializationExtensionsNotSupportedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp attribute duplication..
        /// </summary>
        internal static string TimestampAttributeDuplicate {
            get {
                return ResourceManager.GetString("TimestampAttributeDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp should be a DateTime type..
        /// </summary>
        internal static string TimestampInvalidType {
            get {
                return ResourceManager.GetString("TimestampInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member type &apos;{0}&apos; does not supported..
        /// </summary>
        internal static string ValueAccessorFactoryNotSupportedType {
            get {
                return ResourceManager.GetString("ValueAccessorFactoryNotSupportedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; does not supported..
        /// </summary>
        internal static string WhereTranslatorMemberNotSupported {
            get {
                return ResourceManager.GetString("WhereTranslatorMemberNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator &apos;{0}&apos; does not supported..
        /// </summary>
        internal static string WhereTranslatorOperatorNotSupported {
            get {
                return ResourceManager.GetString("WhereTranslatorOperatorNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to evaluate an expression: &apos;{0}&apos;..
        /// </summary>
        internal static string WhereTranslatorUnableToEvaluateExpression {
            get {
                return ResourceManager.GetString("WhereTranslatorUnableToEvaluateExpression", resourceCulture);
            }
        }
    }
}
